export const AppConfig = () => ({
    PORT: process.env.PORT,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
    DATABASE_URL: process.env.DATABASE_URL,
    PUBLIC_AWS_BUCKET_REGION: process.env.PUBLIC_AWS_BUCKET_REGION,
    PUBLIC_AWS_ACCESS_KEY: process.env.PUBLIC_AWS_ACCESS_KEY,
    AWS_ACCESS_SECRET_KEY: process.env.AWS_ACCESS_SECRET_KEY,
    PUBLIC_AWS_BUCKET_NAME: process.env.PUBLIC_AWS_BUCKET_NAME,
    SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
    SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
    SPOTIFY_REDIRECT_URI: process.env.SPOTIFY_REDIRECT_URI,
    GOOGLE_API_KEY: process.env.GOOGLE_API_KEY,
    GOOGLE_SEARCH_ENGINE_ID: process.env.GOOGLE_SEARCH_ENGINE_ID,
    HUGGING_FACE_TOKEN: process.env.HUGGING_FACE_TOKEN,
    PUBLIC_ROOT_URL: process.env.PUBLIC_ROOT_URL,
    YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY,
    DB_NAME: process.env.DB_NAME,
    DB_USER: process.env.DB_USER,
    DB_PASS: process.env.DB_PASS,
    DB_HOST: process.env.DB_HOST,
    DB_PORT: process.env.DB_PORT,
    MAIL_HOST: process.env.MAIL_HOST,
    MAIL_PORT: process.env.MAIL_PORT,
    MAIL_SECURE: process.env.MAIL_SECURE === 'true',
    MAIL_USER: process.env.MAIL_USER,
    MAIL_PASS: process.env.MAIL_PASS,
    MAIL_FROM: process.env.MAIL_FROM
})